<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE LaTeX_Index
[
  <!ELEMENT LaTeX_Index (Terms*)>
  <!ELEMENT Terms (File*,idx*)>
  <!ATTLIST Terms ApplyTo (All|NamedFiles|AllBut|None) "All"  NotFound (Error|Suppress) "Error">
  <!ELEMENT idx (#PCDATA)>
  <!ELEMENT File (#PCDATA)>
]>
<LaTeX_Index>
<!--
================================================================================

This is a file of indexing terms to apply to a set of LaTeX files.

Each line within <idx> ... </idx> is either an indexing term
or search-string:index-term.
In the second case, the program searches for instances of search-string
and places \index{index-term}% on the line afterwards.

A line without a colon means that the search-term and the index-term
are identical. i.e
   <idx>fribble</idx>
has the same effect as
   <idx>fribble:fribble</idx>

A line with leading plus signs will be stored as is, but the search term will
ignore the plus signs.  This allows the same index term to have multiple
occurrences in the index. For instance
    <idx>virtual-machine</idx>
    <idx>+virtual-machine:Interpreter!virtual machine</idx>
allows the word "virtal-machine" to be indexed by itself and also as a
sub-category of "Interpreter". More than one leading plus sign
is allowed (to cater for several alternative index titles).

Previously ...
   SPACES ARE SIGNIFICANT! (You probably don't want any spaces because the "word
   based" matching will not work: i.e. "bill ben" ~== "bill+ben" and "bill ben"
   will never be a term that is passed to the matcher).  And "virtual-machine"
   is probably better expressed as "virtual+machine"; see below.
   (virtual-machine is one word; virtual+machine is "virtual" followed by
   "machine".  Of course, depending on the text, you might need both).
But now ...
   As a special convenience(tm), the program treats whitespace as a plus sign.
   i.e. "bill     ben" becomes the search term "bill+ben"

Extended Indexing Terms:
========================
The plus sign within a search-term means "before" (i.e. separated by white space
including a line break within a paragraph). So "string+assignment" will match
    blah-blah string     assignmnent is the best thing ...
or
	blah-blah string
    assignment is the best thing ....
or even
    blah-blah string
    % a comment!
    assignment is the best thing ....
but not
    blah-blah string. assignmnent ...
or
	blah-blah string

    assignment is the best thing ...
The last case has a paragraph break (and matching across paragraphs is
suppresssed).

To include some "noise words" between search terms, use term+n+term. For example
"string+5+assignment" will match with up to five other words in between "string"
and "assignmnent".

Note: To preserve idempotency - i.e. idxgen(file) == idxgen(idxgen(file)) -
embedded \index{ ... } commands are treated as comments (and will not cause
further index hits).

Note:  "string+2+assignmnent" WILL match
    blah-blah string. assignment
because the simple minded word distance calculation treats "." as a word.

Alternative Search Terms (using the (...|...|...) syntax:
=========================================================
A search term may contain
alternatives in parenthesis and separated by vertical bars For example
    <idx>(E|e)at(en|ing)+food(|s):Food Consumption</idx>
will generate eight search terms (and index them all under "Food Consumption")
    Eaten+food  Eaten+foods  Eating+food  Eating+foods
    eaten+food  eaten+foods  eating+food  eating+foods
Note that food(|s) generates "food" and "foods", so that
    "(V|v)irtual( |-)machine(|s)
probably catches all the likely variants: note the space in "( |-)". Since the
generation of alternatives happens before the fixing up of embedded spaces, the
expression generates
    "Virtual+machine" "Virtual+machines" "virtual+machine" "virtual+machines"
    "Virtual-machine"  "Virtual-machines" "virtual-machine"  "virtual-machines"	
(the second four are a single word match).
	
LaTeX commands may be matched, but the backslash must be included; for example
<\idx>\Chapter</idx> matches "\Chapter" but not "Chapter" (and <idx>Chapter</idx>
does not match "\Chapter"). If, for some reason, you want both use
     <idx>(|\)Chapter</idx>

All search terms only match within a single LaTeX paragraph. There may be up to
five words in an extended search term.

As a convenience, the LaTeX comment symbol (%) is ignored by the program after
the XML has been parsed (in practice, this means that individual index terms
may be commented out, but % doesn't work as a comment except in <idx>  </idx>)
and at the beginning of the index term. i.e. <idx>% blah blah</idx> will work
but <idx>blah % blah<idx> probably wont.

<idx> terms are grouped together in a <Terms> tag.
The attributes of the tag govern what is done with the <idx> terms within it.

ApplyTo="All" (Default)
    The <idx> terms in the group are applied to all files.
ApplyTo="NamedFiles"
    Each of the files (named in a <File> ... </File> tag) will be searched
    for the specified <idx> terms.
ApplyTo="AllBut"
    All of the files (except those named in any <File> ... </File> tag) will 
    be searched for the specified <idx> terms.
ApplyTo="None"
    The <idx> terms will be ignored (useful for temporarily suppressing a
    group of <idx> terms without commenting each of them away with %).

NotFound="Error" (Default)
    An <idx> term that results in no hits will be reported.
NotFound="Suppress"
    Suppress "not found" reporting for the <idx> terms in the group.

================================================================================
================================================================================

The following index terms started off by being extracted from the IBV6 index PDF.
After that, they got added to and extended.

-->


<!-- A list of index terms that are known not to be present in
     any file and are not to be reported as absent.             -->
<Terms NotFound="Suppress">
<idx>SITBOL</idx><!-- When Appendix E (Future Projects) is resurrected ... -->
<idx>(M|m)ethod+variable(|s):Variable!method variable</idx>
</Terms>

<!--
    These index terms have been added (or should be added) manually to the files
	so we don't need to (or actually can't, in the case of C++)  index them automatically
-->
<Terms ApplyTo="None">
<!-- These have been added -->
<idx>adjust:C functions!adjust</idx>
<idx>cater:C functions!cater</idx>
<idx>hash::C functions!hash</idx>
<idx>scollect:C functions!scollect@\protect\texttt{scollect}</idx>
<!-- These are still to do ... -->
<idx>%C++</idx> <!-- This is a syntax error; Oops -->
<idx>Control expressions</idx>
<idx>Range specifications</idx>
</Terms>

<!-- A fine collection of languages -->
<Terms>
<idx>Algol</idx>
<idx>Alphard</idx>
<idx>APL</idx>
<idx>CLU</idx>
<idx>InterLisp</idx>
<idx>IPL-V</idx>
<idx>LISP</idx>
<idx>Pascal</idx>
<idx>PL+2+I:PL/I</idx> <!-- "PL/I" is treated as two words "PL" and "I" with a / between them -->
<idx>Prolog</idx>
<idx>Python:Python</idx>
<idx>Ratfor</idx>
<idx>SETL</idx>
<idx>SL5</idx>
<idx>SNOBOL+1+4:SNOBOL4</idx>
<idx>SNOBOL4</idx>
</Terms>

<!-- To do: These are too all-encompassing. See if they're really needed -->
<Terms ApplyTo="None">
<idx>+data</idx>
<idx>+value</idx>
<idx>+size</idx>
<idx>+Pointer</idx>
<idx>+Pointers</idx>
<idx>computed</idx>
<idx>Characters</idx>
</Terms>

<!-- To do: review these and either remove them, or move them to A .. Z -->
<Terms>
<idx>Conjunction operations</idx>
<idx>Conversion</idx>
<idx>Copying values</idx>
<idx>Data objects</idx>
<idx>Data structures</idx>
<idx>Declarations</idx>
<idx>Efficiency</idx>
<idx>Element generation</idx>
<idx>Elements</idx>
<idx>Expressions</idx>
<idx>FncDcl</idx><!-- This should be a fossil, but isn't -->
<idx>Function calls</idx>
<idx>Functions</idx>
<idx>Identifiers</idx>
<idx>Invocation expressions</idx>
<idx>Iteration</idx>
<idx>limitation expressions</idx>
<idx>Lookup</idx>
<idx>Mapping characters</idx>
<idx>mapping</idx>
<idx>matching</idx>
<idx>Offset</idx>
<idx>Operators</idx>
<idx>Performance</idx>
<idx>Positions in strings</idx>
<idx>referencing</idx>
<idx>Results</idx>
<idx>scalar</idx>
<idx>Scope resolution</idx>
<idx>Selection expressions</idx>
<idx>Side effects</idx>
<idx>Size limitation(|s):Size limitation</idx>
<idx>Size operation(|s):Size operation</idx>
<idx>Storage allocation</idx>
<idx>Storage management</idx>
<idx>Structure declarations</idx>
<idx>Structures</idx>
<idx>Subscripting expressions</idx>
<idx>Support routines</idx>
<idx>Suspend</idx>
<idx>Values</idx>
</Terms>

<Terms ApplyTo="AllBut">
  <File>ib.tex</File>
  <File>appB.tex</File>
  <File>appC.tex</File>
  <File>p1-interpreter.tex</File>
<idx>+swap:swap</idx>
</Terms>

<!-- Index terms beginning with A -->
<Terms>
<idx>(A|a)llocated+block+region:Allocated block region</idx>
<idx>address spaces:Address spaces</idx>
<idx>Allocation</idx>
<idx>(A|a)lternation:Alternation</idx>
<idx>(A|a)lternation+6+expression(|s):Alternation expressions</idx>

<idx>(A|a)llocated+string+region(|s):Allocated string region</idx>
<idx>(A|a)pplicative+3+operation(|s):Applicative Operation</idx>
<idx>+argp:argp@\protect\texttt{argp}</idx>
<!-- Arguments -->
<idx>(E|e)valuation+3+argument(|s):Arguments!evaluation</idx>
<idx>(A|a)rgument+evaluation:Arguments!evaluation</idx>
<idx>extra+3+argument(|s):Arguments!extra</idx>
<idx>(A|a)rgument+list+adjustment:Argument list adjustment</idx>
<idx>(A|a)rgument+(P|p)rocessing:Argument list adjustment</idx>
<idx>+(A|a)rgument+(P|p)rocessing:Argument processing</idx>
<idx>Argument+Transmission:Argument transmission</idx>
<idx>(variable|arbitrary)+number+3+arguments:Arguments!variable number of</idx>
<idx>omitted+argument(|s):Arguments!omitted</idx>
<idx>argument(|s)+2+omitted:Arguments!omitted</idx>
<idx>argument(|s)+5+operat(or|ion):Arguments!operator</idx>
<idx>(O|o)perator+(A|a)rgument(|s):Arguments!operator</idx>
<idx>argument(|s)+5+procedure:Arguments!procedure</idx>
<idx>(P|p)rocedure+(A|a)rgument(|s):Arguments!procedure</idx>
<idx>argument(|s)+5+function:Arguments!function</idx>
<idx>(F|f)unction+(A|a)rgument(|s):Arguments!function</idx>

<idx>%-% No hits %%argument(|s)+5+preserv(e|ed|ation):Arguments!preservation of</idx>
<idx>%-% No hits %%preserv(e|ation)+5+argument(|s):Arguments!preservation of</idx>

<idx>arithmetic overflow:Arithmetic!arithmetic overflow</idx>
<idx>real+4+arithmetic:Arithmetic!real arithmetic</idx>
<idx>integer+4+arithmetic:Arithmetic!integer arithmetic</idx>
<idx>pointer+4+arithmetic:Arithmetic!pointer arithmetic</idx>
<idx>fixed+point+4+arithmetic:Arithmetic!fixed point arithmetic</idx>

<idx>ASCII</idx>
<idx>(A|a)ssembly(-|+)language:Assembly language</idx>

<idx>assign(ment|ed)+to:Assignment operations</idx>
<idx>\(|sub)section+12+Assignment:Assignment</idx>

<idx>(left+3+|left-|right+3+|right-)associative:Associativity</idx>
<idx>(A|a)ssociative+look(|up|+up|-up):Associative lookup</idx>

<idx>(A|a)ugmented+assignment+operation(|s):Augmented assignment operations</idx>
</Terms>

<!-- Index terms beginning with B -->

<!-- "basis" is used too widely in the text, so we restrict indexing it
	 to the storage chapter (and answers to questions). -->
<Terms ApplyTo="NamedFiles">
  <File>p1-storage.tex</File>
  <File>app-solutions.tex</File>
<idx>(B|b)asis:Basis, the</idx>
<idx>+(B|b)asis:Garbage collection!basis</idx>
</Terms>

<Terms>
<idx>(B|b)ack+chain:Back chain</idx>
<idx>Backtracking</idx>
<idx>(C|c)ontrol+backtracking:Backtracking!control</idx>
<idx>(D|d)ata backtracking:Backtracking!data</idx>
<idx>(B|b)ig(+|-)(I|i)nhale:Big inhale@``Big inhale''</idx>
<idx>bit+value:Bits</idx>
<idx>(T|t)able-element+block(|s):Blocks!Table-element</idx>
<idx>(T|t)able-element+2+trapped(+|-)variable+2+block(|s):Blocks!Table-element!Trapped variable</idx>
<idx>(T|t)able-header+block(|s):Blocks!Table-header</idx>
<idx>(B|b)lock+3+size(|s):Block size</idx>
<idx>size(|s)+3+(B|b)lock(|s):Block size</idx>
<idx>(T|t)itle(|s)+6+(type|block)(|s):Block titles</idx>
<idx>block+title(|s):Block titles</idx>
<idx>(B|b)ounded+(E|e)xpression(|s):Bounded expressions</idx>
<idx>(B|b)reathing(-|+)room:Breathing room</idx>
<idx>(B|b)uffer(|s):Buffer</idx>
</Terms>

<!-- Index terms beginning with C -->
<Terms ApplyTo="AllBut">
  <File>appC.tex</File>
  <!-- There are a lot of spurious matches of
	   C functions with VM instructions -->
<idx>addmem:C functions!addmem@\protect\texttt{addmem}</idx>
<idx>alcblk:C functions!alcblk@\protect\texttt{alcblk}</idx>
<idx>alccoexp:C functions!alccoexp@\protect\texttt{alccoexp}</idx>
<idx>alcfile:C functions!alcfile@\protect\texttt{alcfile}</idx>
<idx>alclint:C functions!alclint@\protect\texttt{alclint}</idx>
<idx>alclist:C functions!alclist@\protect\texttt{alclist}</idx>
<idx>alclstb:C functions!alclstb@\protect\texttt{alclstb}</idx>
<idx>alcreal:C functions!alcreal@\protect\texttt{alcreal}</idx>
<idx>alcrecd:C functions!alcrecd@\protect\texttt{alcrecd}</idx>
<idx>alcrefresh:C functions!alcrefresh@\protect\texttt{alcrefresh}</idx>
<idx>alcselem:C functions!alcselem@\protect\texttt{alcselem}</idx>
<idx>alcset:C functions!alcset@\protect\texttt{alcset}</idx>
<idx>alcstr:C functions!alcstr@\protect\texttt{alcstr}</idx>
<idx>alcsubs:C functions!alcsubs@\protect\texttt{alcsubs}</idx>
<idx>alctable:C functions!alctable@\protect\texttt{alctable}</idx>
<idx>alctelem:C functions!alctelem@\protect\texttt{alctelem}</idx>
<idx>alctvtbl:C functions!alctvtbl@\protect\texttt{alctvtbl}</idx>
<idx>anycmp:C functions!anycmp@\protect\texttt{anycmp}</idx>
<idx>asgn:C functions!asgn@\protect\texttt{asgn}</idx>
<idx>blkdump:C functions!blkdump@\protect\texttt{blkdump}</idx>
<idx>blkreq:C functions!blkreq@\protect\texttt{blkreq}</idx>
<idx>cofree:C functions!cofree@\protect\texttt{cofree}</idx>
<idx>coswitch:C functions!coswitch@\protect\texttt{coswitch}</idx>
<idx>cplist:C functions!cplist@\protect\texttt{cplist}</idx>
<idx>cnv\_cset:C functions!cnv\_cset@\protect\texttt{cnv\_cset}</idx>
<idx>cnv\_int:C functions!cnv\_int@\protect\texttt{cnv\_int}</idx>
<idx>cvpos:C functions!cvpos@\protect\texttt{cvpos}</idx>
<idx>cnv\_real:C functions!cnv\_real@\protect\texttt{cnv\_real}</idx>
<idx>cnv\_str:C functions!cnv\_str@\protect\texttt{cnv\_str}</idx>
<idx>def\_int:C functions!def\_int@\protect\texttt{def\_int}</idx>
<idx>def\_cset:C functions!def\_cset@\protect\texttt{def\_cset}</idx>
<idx>deref:C functions!deref@\protect\texttt{deref}</idx>
<idx>descr:C functions!descr@\protect\texttt{descr}</idx>
<idx>equiv:C functions!equiv@\protect\texttt{equiv}</idx>
<idx>find+5+function:C functions!find@\protect\texttt{find}</idx>
<idx>function+5+find:C functions!find@\protect\texttt{find}</idx>
<idx>result+6+find:C functions!find@\protect\texttt{find}</idx>
<idx>find+6+result:C functions!find@\protect\texttt{find}</idx>
<idx>getstr:C functions!getstr@\protect\texttt{getstr}</idx>
<idx>interp:C functions!interp@\protect\texttt{interp}</idx>
<idx>lexcmp:C functions!lexcmp@\protect\texttt{lexcmp}</idx>
<idx>malloc:C functions!malloc@\protect\texttt{malloc}</idx>
<idx>memb:C functions!memb@\protect\texttt{memb}</idx>
<idx>mvc:C functions!mvc@\protect\texttt{mvc}</idx>
<idx>numcmp:C functions!numcmp@\protect\texttt{numcmp}</idx>
<idx>convert(|s)+5+numeric:C functions!numeric@\protect\texttt{numeric}</idx>
<idx>numeric+5+convert(|s):C functions!numeric@\protect\texttt{numeric}</idx>
<idx>postqual:C functions!postqual@\protect\texttt{postqual}</idx>
<idx>routine(|s)+8+free:C functions!free@\protect\texttt{free}</idx>
<idx>markblock:C functions!markblock@\protect\texttt{markblock}</idx>
<idx>routine+2+order:C functions!order@\protect\texttt{order}</idx>
<idx>outimage:C functions!outimage@\protect\texttt{outimage}</idx>
<idx>putstr:C functions!putstr@\protect\texttt{putstr}</idx>
<idx>qsort:C functions!qsort@\protect\texttt{qsort}</idx>
<idx>qtos:C functions!qtos@\protect\texttt{qtos}</idx>
<idx>repl:C functions!repl@\protect\texttt{repl}</idx>
<idx>runerr:C functions!runerr@\protect\texttt{runerr}</idx>
<idx>strprc:C functions!strprc@\protect\texttt{strprc}</idx>
<idx>strreq:C functions!strreq@\protect\texttt{strreq}</idx>
<idx>sweep:C functions!sweep@\protect\texttt{sweep}</idx>
<idx>syserr:C functions!syserr@\protect\texttt{syserr}</idx>
</Terms>

<Terms>
<idx>CDC+Cyber:CDC Cyber</idx>
<idx>C+double(|s):C double</idx> 

<idx>C+(F|f)rame(|s):C!C Frames</idx>
<idx>C+programming+language:C!Programming language</idx>
<idx>C+state:C!C state</idx>
<idx>C+string(|s):C!C strings</idx>
<idx>C+structure(|s):C!C structures</idx>

<idx>set(|s)+of+characters:Character sets</idx>
<idx>circular+3+queue(|s):Circular Queue</idx>
<idx>collating+sequence:Collating sequence</idx>
<idx>(C|c)ontext+switch:Context Switch</idx>
<idx>(C|c)omparison+operation(|s):Comparison operations</idx>
<idx>(C|c)omparison+routine(|s):Comparison routines</idx>
<idx>routine(|s)+15+(C|c)omparison(|s):Comparison routines</idx>
<idx>compilation+25+compiler:Compilation</idx>
<idx>compiler+25+compilation:Compilation</idx>
<idx>(S|s)eparate+compilation:Compilation</idx>
<idx>(C|c)onditional+compilation:Compilation</idx>
<idx>+(S|s)eparate+compilation:Compilation!separate</idx>
<idx>+(C|c)onditional+compilation:Compilation!conditional</idx>
<idx>(C|c)ompound+expression(|s):Compound expressions</idx>
<idx>computer+architecture:Computer architecture</idx>
<idx>(C|c)o-expression(|s):Co--expression</idx>
<idx>activation:Co--expression!activation</idx>
<idx>(C|c)o-expression+block(|s):Co--expression blocks</idx>
<idx>(R|r)efresh+block(|s):Co--expression!refresh block</idx>
<idx>(C|c)o-expression+8+refresh(|ed):Co--expression!refresh</idx>
<idx>refresh(|ed)+8+(C|c)o-expression:Co--expression!refresh</idx>
<idx>Constants</idx>
<idx>(C|c)set(|s):Csets</idx>
<idx>(C|c)set+4+literal(|s):Cset literals</idx>
<idx>(C|c)set block(|s):Cset blocks</idx>
<idx>+(C|c)ontrol+backtracking:Control backtracking</idx>

<idx>(C|c)ontrol+(S|s)tructure(|s):Control structures</idx>
<idx>break+4+expression(|s):Control structures!break@\protect\texttt{break} expression</idx>
<idx>(\textttt|\iconline)+4+break:Control structures!break@\protect\texttt{break} expression</idx>
<idx>case+4+clause(|s):Control structures!case@\protect\texttt{case} clause</idx>
<idx>case+2+expression(|s):Control structures!case@\protect\texttt{case} expression</idx>
<idx>create+4+expression(|s):Control structures!create@\protect\texttt{create} expression</idx>
<idx>every-do:Control structures!every@\protect\texttt{every--do} expression</idx>
<idx>fail+4+expression(|s):Control structures!fail@\protect\texttt{fail} expression</idx>
<idx>expression+4+fail:Control structures!fail@\protect\texttt{fail} expression</idx>
<idx>if-then-else+expression:Control structures!if@\protect\texttt{if--then--else} expression</idx>
<idx>not+4+expression(|s):Control structures!not@\protect\texttt{not} expression</idx>
<idx>next+4+expression(|s):Control structures!next@\protect\texttt{next} expression</idx>
<idx>return+expression(|s):Control structures!return@\protect\texttt{return} expression</idx>
<idx>repeat+expression(|s):Control structures!repeat@\protect\texttt{repeat} expression</idx>
<idx>(R|r)epeated+(A|a)lternation:Control structures!repeated alternation expressions</idx>
<idx>suspend+expression(|s):Control structures!suspend@\protect\texttt{suspend} expression</idx>
<idx>+until+2+do:Control Structures!until@\protect\texttt{until--do} expression</idx>
<idx>while-do:Control structures!while@\protect\texttt{while--do} expression</idx>
<idx>+(\textttt|\iconline)+4+case:Control structures!case@\protect\texttt{case} clause</idx>
<idx>(\textttt|\iconline)+4+case:Control structures!case@\protect\texttt{case} expression</idx>
<idx>(\textttt|\iconline)+4+create:Control structures!create@\protect\texttt{create} expression</idx>
<idx>(\textttt|\iconline)+4+every:Control structures!every@\protect\texttt{every--do} expression</idx>
<idx>(\textttt|\iconline)+4+fail:Control structures!fail@\protect\texttt{fail} expression</idx>
<idx>(\textttt|\iconline)+4+expression:Control structures!fail@\protect\texttt{fail} expression</idx>
<idx>(\textttt|\iconline)+4+if:Control structures!if@\protect\texttt{if--then--else} expression</idx>
<idx>(\textttt|\iconline)+4+not:Control structures!not@\protect\texttt{not} expression</idx>
<idx>(\textttt|\iconline)+4+next:Control structures!next@\protect\texttt{next} expression</idx>
<idx>(\textttt|\iconline)+4+return:Control structures!return@\protect\texttt{return} expression</idx>
<idx>(\textttt|\iconline)+4+repeat:Control structures!repeat@\protect\texttt{repeat} expression</idx>
<idx>(\textttt|\iconline)+4+suspend:Control structures!suspend@\protect\texttt{suspend} expression</idx>
<idx>(\textttt|\iconline)+4++until:Control Structures!until@\protect\texttt{until--do} expression</idx>
<idx>(\textttt|\iconline)+4+while:Control structures!while@\protect\texttt{while--do} expression</idx>

<idx>C+stack:C!C stack</idx>
<idx>C+stack+overflow:C!C stack overflow</idx>
<idx>C+stack+registers:C!C stack registers</idx>

<idx>downward-growing+3+stack:C stack!downward-growing</idx>
<idx>upward-growing+3+stack:C stack!upward-growing</idx>
<idx>(U|u)nwind(|s|ing):C stack!unwinding</idx>
<idx>built-in+4+cset(|s):Csets!built-in</idx>
</Terms>

<!-- Index terms beginning with D -->
<Terms>
<idx>+(D|d)ata+backtracking:Data backtracking</idx>
<idx>first-class+3+data:Data Objects, first-class</idx>
<idx>(D|d)ata+type(|s):Data type</idx>
<idx>(C|c)onver(ting|sion|t|ted)+3+(type|data+type)(|s):Data type!conversion of</idx>
<idx>type(|s)+4+integer:Data type!integer</idx>
<idx>(I|i)nteger+4+type(|s):Data type!integer</idx>
<idx>(T|t)ype+3+conver(ting|sion|t|ted):Data type!conversion of</idx>
<idx>conversion+of+4+to:Data type!conversion of</idx>
<idx>(D|d)ead+2+(O|o)bject(|s):Dead objects</idx>
<idx>Debugging</idx>
<idx>DEC-10</idx>
<idx>default clause(|s):Default clause</idx>
<idx>Defaults</idx>
<idx>(D|d)efined+constant(|s):Defined constant</idx>
<idx>CsetSize:Defined constant!CsetSize@\protect\texttt{CsetSize}</idx>
<idx>IntBits:Defined constant!IntBits@\protect\texttt{IntBits}</idx>
<idx>LogHuge:Defined constant!LogHuge@\protect\texttt{LogHuge}</idx>
<idx>LogIntSize:Defined constant!LogIntSize@\protect\texttt{LogIntSize}</idx>
<idx>MaxCvtLen:Defined constant!MaxCvtLen@\protect\texttt{MaxCvtLen}</idx>
<idx>MaxLong:Defined constant!MaxLong@\protect\texttt{MaxLong}</idx>
<idx>MaxShort:Defined constant!MaxShort@\protect\texttt{MaxShort}</idx>
<idx>MaxStrLen:Defined constant!MaxStrLen@\protect\texttt{MaxStrLen}</idx>
<idx>MinListSlots:Defined constant!MinListSlots@\protect\texttt{MinListSlots}</idx>
<idx>MinLong:Defined constant!MinLong@\protect\texttt{MinLong}</idx>
<idx>MinShort:Defined constant!MinShort@\protect\texttt{MinShort}</idx>
<idx>WordSize:Defined constant!WordSize@\protect\texttt{WordSize}</idx>
<idx>WordBits:Defined constant!WordBits@\protect\texttt{WordBits}</idx>
<idx>(D|d)ereferenc(ed|ing):Dereferencing</idx>

<idx>Descriptors</idx>
<idx>(T|t)ended+2+(D|d)escriptor(|s):Descriptors!tended</idx>
<idx>d-word:Descriptors!d-word</idx>
<idx>v-word:Descriptors!v-word</idx>
<idx>(N|n)ull+2+descriptor(|s):Descriptors!null</idx>
<idx>(D|d)iagnostic(|s):Diagnostics</idx>
</Terms>

<!-- Index terms beginning with E -->
<Terms>
<idx>EBCDIC</idx>
<idx>empty+list:Empty List</idx>
<idx>empty+string:Empty String</idx>
<idx>empty+table:Empty Table</idx>
<idx>empty+set:Empty Set</idx>
<idx>(E|e)rror+message(|s):Error Message</idx>
<idx>(E|e)rror+check(|s|ing):Error checking</idx>
<idx>(E|e)rror+termination:Error termination</idx>

<idx>black+hole(|s):Evaluation of expressions!black holes</idx>
<idx>(O|o)rder+3+(E|e)valuation:Expressions!evaluation order</idx>
<idx>(E|e)valuation+3+expression(|s):Expressions!evaluation of</idx>
<idx>(E|e)xpression-evaluation:Expressions!evaluation of</idx>
<idx>(R|r)esum(e|ing|ption)(|+of)+3+(E|e)xpression(|s):Expressions!resumption of</idx>
<idx>++(R|r)epeated+(A|a)lternation:Expressions!repeated alternation</idx>
<idx>outcome+10+expression:Expressions!evaluation outcome</idx>
<idx>(E|e)xpression+frame+pointer(|s):Expressions!frame pointer (efp)</idx>
<idx>+efp:Expressions!frame pointer (efp)</idx>
<idx>to-by+2+expression(|s):Expressions!to-by</idx>
<idx>until-do+expression(|s):Expressions!until-do</idx>
<idx>until+2+do:Expressions!until-do</idx>
</Terms>

<!-- Index terms beginning with F -->
<Terms>
<idx>Failure</idx>
<idx>field+name(|s):Field Names</idx>
<idx>name(s|d)+3+field(|s):Field Names</idx>
<idx>field+reference(|s):Field References</idx>
<idx>(O|o)pen(|ed)+12+option(|s):File!Open options</idx>
<idx>close(|s)+5+file:File!closing</idx>
<idx>(O|o)pen(|s|ing)+5+file:File!opening</idx>
<idx>(E|e)nd(+of+|-of-)file:File!end of file</idx>
<idx>Files:File</idx>
<idx>(F|f)ile+(O|o)rganization:File Organization</idx>
<idx>%-% Too many hits %% file</idx>
<idx>file+status:File!file status</idx>
<idx>\texttt+5+flag(|s):Flags</idx>
<idx>\texttt+2+n+3+flag(|s):Flags!n@\protect\texttt{n} flag</idx>
<idx>\texttt+2+p+3+flag(|s):Flags!p@\protect\texttt{p} flag</idx>
<idx>\texttt+2+t+3+flag(|s):Flags!t@\protect\texttt{t} flag</idx>
<idx>\texttt+2+v+3+flag(|s):Flags!v@\protect\texttt{v} flag</idx>
<idx>Frames</idx>
<idx>(P|p)rocedure+(F|f)rame(|s):Frames!procedure</idx>
<idx>(E|e)xpression+(F|f)rame(|s):Frames!expression</idx>
<idx>(G|g)enerator+(F|f)rame(|s):Frames!generator</idx>
<idx>(F|f)ree+list:Free list</idx>
<idx>(F|f)ree+(S|s)pace:Free space</idx>
<idx>built-in+4+function(|s):Functions!built-in</idx>
<idx>return(|ing)+from+3+(F|f)unction:Functions!returning from</idx>
</Terms>

<!-- Index terms beginning with G -->
<Terms>
<idx>{G|g)arbage+(C|c)ollection:Garbage collection</idx>
<idx>(C|c)ompaction:Garbage collection!compaction</idx>
<idx>(L|l)ocation+(P|p)hase:Garbage collection!location</idx>
<idx>(P|p)ointer (A|a)djustment(|s):Garbage collection!pointer adjustment</idx>
<idx>GC+(T|t)hread:Garbage collection!thread</idx>
<idx>GC+(M|m)utex:Garbage collection!mutex</idx>
<idx>(G|g)arbage+(C|c)ollection+2+(M|m)utex:Garbage collection!mutex</idx>
<idx>Generation</idx>
<idx>+generator:Generators</idx>
<idx>Generator(|s):Generators</idx>
<idx>generator frame pointer:Generator frame pointer</idx>
<idx>+gfp:gfp@\protect\texttt{gfp}</idx>

<idx>(G|g)lobal+declaration(|s):Global declarations</idx>
<idx>(G|g)lobal+identifier(|s):Global identifiers</idx>
<idx>(G|g)enerative+(C|c)ontrol+(S|s)tructure(|s):Generative control structures</idx>
<idx>(G|g)oal(-|+)directed+evaluation:Goal-directed evaluation</idx>
</Terms>

<!-- Index terms beginning with H -->
<Terms>
<idx>(C|c)omput(ing|ation)+4+hash:Hash computations</idx>
<idx>(H|h)ash+(calcul|comput)ation(|s):Hash computations</idx>
<idx>(H|h)ash+look(-|+)up:Hash lookup</idx>
<idx>look(|-|+)up+15+hash:Hash lookup</idx>
<idx>(H|h)ash number(|s):Hash number</idx>
<idx>(H|h)eader+file(|s):Header files</idx>
<idx>(H|h)eap(|s):Heap</idx>
<idx>(P|p)rivate+2+(H|h)eap(|s):Heap!private</idx>
<idx>(H|h)eap(|s)+2+(P|p)rivate:Heap!private</idx>
<idx>(P|p)ublic+2+(H|h)eap(|s):Heap!public</idx>
<idx>(H|h)eap(|s)+2+(P|p)ublic:Heap!public</idx>
<idx>(H|h)eterog(eneous|eneity):Heterogeneous structures</idx>
<idx>(H|h)euristic(|s):Heuristics</idx>
<idx>human+frailty:Human frailty</idx>
</Terms>

<!-- Index terms beginning with I -->
<Terms>
<idx>IBM+1+370:IBM 370</idx>

<idx>Icode</idx>
<idx>(I|i)code+file(|s):Icode!files</idx>
<idx>(I|i)code+region:Icode!Region</idx>

<idx>Icon functions</idx>
<idx>+close+5+file:Icon functions!close@\protect\texttt{close}</idx>
<idx>+open+5+file:Icon functions!open@\protect\texttt{open}</idx>
<idx>+function+3+display:Icon functions!display@\protect\texttt{display}</idx>
<idx>+function+3+image:Icon functions!image@\protect\texttt{image}</idx>
<idx>+function+3+type:Icon functions!type@\protect\texttt{type}</idx>
<idx>(\texttt|\iconline)+4+close:Icon functions!close@\protect\texttt{close}</idx>
<idx>(\texttt|\iconline)+4+copy:Icon functions!copy@\protect\texttt{copy}</idx>
<idx>(\texttt|\iconline)+4+delete:Icon functions!delete@\protect\texttt{delete}</idx>
<idx>(\texttt|\iconline)+4+display:Icon functions!display@\protect\texttt{display}</idx>
<idx>(\texttt|\iconline)+4+find:Icon functions!find@\protect\texttt{find}</idx>
<idx>(\texttt|\iconline)+4+get:Icon functions!get@\protect\texttt{get}</idx>
<idx>(\texttt|\iconline)+4+image:Icon functions!image@\protect\texttt{image}</idx>
<idx>(\texttt|\iconline)+4+insert:Icon functions!insert@\protect\texttt{insert}</idx>
<idx>(\texttt|\iconline)+4+left:Icon functions!left@\protect\texttt{left}</idx>
<idx>(\texttt|\iconline)+4+list:Icon functions!list@\protect\texttt{list}</idx>
<idx>(\texttt|\iconline)+4+map:Icon functions!map@\protect\texttt{map}</idx>
<idx>(\texttt|\iconline)+4+member:Icon functions!member@\protect\texttt{member}</idx>
<idx>(\texttt|\iconline)+4+move:Icon functions!move@\protect\texttt{move}</idx>
<idx>(\texttt|\iconline)+4+numeric:Icon functions!numeric@\protect\texttt{numeric}</idx>
<idx>(\texttt|\iconline)+4+open:Icon functions!open@\protect\texttt{open}</idx>
<idx>(\texttt|\iconline)+4+pop:Icon functions!pop@\protect\texttt{pop}</idx>
<idx>(\texttt|\iconline)+4+pull:Icon functions!pull@\protect\texttt{pull}</idx>
<idx>(\texttt|\iconline)+4+push:Icon functions!push@\protect\texttt{push}</idx>
<idx>(\texttt|\iconline)+4+put:Icon functions!put@\protect\texttt{put}</idx>
<idx>(\texttt|\iconline)+4+read:Icon functions!read@\protect\texttt{read}</idx>
<idx>(\texttt|\iconline)+4+reads:Icon functions!reads@\protect\texttt{reads}</idx>
<idx>(\texttt|\iconline)+4+repl:Icon functions!repl@\protect\texttt{repl}</idx>
<idx>(\texttt|\iconline)+4+reverse:Icon functions!reverse@\protect\texttt{reverse}</idx>
<idx>(\texttt|\iconline)+4+set:Icon functions!set@\protect\texttt{set}</idx>
<idx>(\texttt|\iconline)+4+sort:Icon functions!sort@\protect\texttt{sort}</idx>
<idx>(\texttt|\iconline)+4+stop:Icon functions!stop@\protect\texttt{stop}</idx>